name = "bemyteammate-push"
main = "worker.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "bdbaa1ee442f4b75b490f9dce8a8d162"

[vars]
# Set in Cloudflare as secrets instead of here:
# FCM_PROJECT_ID, FCM_CLIENT_EMAIL, FCM_PRIVATE_KEY

[triggers]
crons = ["30 22 * * *", "30 23 * * *"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[observability.traces]
enabled = false
